repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
      - id: go-fmt
      - id: go-unit-tests
      - id: go-imports
      - id: go-build
      - id: go-mod-tidy
      - id: golangci-lint
