// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: tracer/grpc_example/service.proto

package grpc_example

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ExampleGRPCService_Ping_FullMethodName = "/ExampleGRPCService/Ping"
)

// ExampleGRPCServiceClient is the client API for ExampleGRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExampleGRPCServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type exampleGRPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExampleGRPCServiceClient(cc grpc.ClientConnInterface) ExampleGRPCServiceClient {
	return &exampleGRPCServiceClient{cc}
}

func (c *exampleGRPCServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, ExampleGRPCService_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleGRPCServiceServer is the server API for ExampleGRPCService service.
// All implementations must embed UnimplementedExampleGRPCServiceServer
// for forward compatibility
type ExampleGRPCServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedExampleGRPCServiceServer()
}

// UnimplementedExampleGRPCServiceServer must be embedded to have forward compatible implementations.
type UnimplementedExampleGRPCServiceServer struct {
}

func (UnimplementedExampleGRPCServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedExampleGRPCServiceServer) mustEmbedUnimplementedExampleGRPCServiceServer() {}

// UnsafeExampleGRPCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExampleGRPCServiceServer will
// result in compilation errors.
type UnsafeExampleGRPCServiceServer interface {
	mustEmbedUnimplementedExampleGRPCServiceServer()
}

func RegisterExampleGRPCServiceServer(s grpc.ServiceRegistrar, srv ExampleGRPCServiceServer) {
	s.RegisterService(&ExampleGRPCService_ServiceDesc, srv)
}

func _ExampleGRPCService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleGRPCServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExampleGRPCService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleGRPCServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExampleGRPCService_ServiceDesc is the grpc.ServiceDesc for ExampleGRPCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExampleGRPCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ExampleGRPCService",
	HandlerType: (*ExampleGRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ExampleGRPCService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tracer/grpc_example/service.proto",
}
